library(tidyverse)
library(dplyr)
mecha_mpg <- read.csv(file='MechaCar_mpg.csv', check.names=F, stringsAsFactors=F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha_mpg))
mecha_coils <- read.csv(file='Suspension_Coil.csv', check.names=F, stringsAsFactors=F)
total_summary <- mecha_coils %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary <- mecha_coils %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
t.test(mecha_coils$PSI, mu=1500)
Lot1 <- subset(mecha_coils, Manufacturing_Lot == "Lot1")
t.test(Lot1$PSI, mu=1500)
Lot2 <- subset(mecha_coils, Manufacturing_Lot == "Lot2") 
t.test(Lot2$PSI, mu=1500)
Lot3 <- subset(mecha_coils, Manufacturing_Lot == "Lot3")
t.test(Lot3$PSI, mu=1500)
